development: &non_production_settings
  :site:
    :address: "http://localhost:3000"

test:
  <<: *non_production_settings

production:
  :google_analytics:
    :api_key: "[Enter Google ID]"
  :site:
    :address: "[Address]"